version: "3.9"

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      -  .:/app
    environment:
      -  PYTHONBUFFERED=1
      -  DATABASE_URL=postgresql://postgres:postgres@db:5432/varion-todo
    depends_on:
      - db
  db:
    image: postgres:14.17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: varion-todo
    volumes:
      -  pgdata:/var/lib/postgresql/data
    ports:
      -  "5432:5432"

volumes:
  pgdata:
